name: Prune Old Container Images

on:
  schedule:
    # Run weekly (every Sunday at midnight)
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      keep_last_n:
        description: 'Number of recent images to keep (per tag pattern)'
        required: false
        default: '10'
      older_than_days:
        description: 'Delete images older than X days'
        required: false
        default: '30'

jobs:
  prune-images:
    name: Delete old container images
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'hap-ctf'
          package-type: 'container'
          min-versions-to-keep: ${{ github.event.inputs.keep_last_n || 10 }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: false
          older-than: ${{ github.event.inputs.older_than_days || 30 }} # days
