name: Test and Build

on:
    push:
      branches:
        - main
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # test:
    # name: Test
    # runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v4

    #   - uses: PalisadeResearch/ci-action@master
    #     with:
    #       github_access_token: ${{ github.token }}

    #   - run: pytest -v

  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: PalisadeResearch/ci-action@master
        with:
          github_access_token: ${{ github.token }}

      - run: |
          export HAP_CTF_TAR_GZ=$(nix build --no-link --print-out-paths .#docker)
          export HAP_CTF_IMAGE=$(docker load -q -i "$HAP_CTF_TAR_GZ" | awk -F': ' '{print $2}')
          docker tag "$HAP_CTF_IMAGE" ghcr.io/palisaderesearch/hap-ctf:latest

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - run: docker push ghcr.io/palisaderesearch/hap-ctf:latest
